### ISSUE TITLE
createTestManager is not a function

### ISSUE THREAD

**Issue by manelmadeira** [nfl/react-gpt#42]
When using the version 0.2.4, we were using `createTestManager` to mock GPT on our mocha tests (as documented [here](https://github.com/nfl/react-gpt/blob/master/docs/Guides.md#test-mode), but when updating to 0.2.5 we start getting the `GPT.createTestManager is not a function.`.

Can you please update the docs?

Thanks.

**Comment by patrick-mcdougle** [comment]
I think it might just be `testManager()`. See https://github.com/nfl/react-gpt/blob/master/src/Bling.js#L360

**Comment by potench** [comment]
I might need to look into this more (and update the docs), but in case it helps there's a `createManagerTest` util class 
https://github.com/nfl/react-gpt/blob/f73958e7e3c88931b4e14c4e6a8ded80d2fba31f/src/utils/createManagerTest.js

And here's an example using it https://github.com/nfl/react-gpt/blob/f73958e7e3c88931b4e14c4e6a8ded80d2fba31f/test/Bling.spec.js#L17
